<!DOCTYPE html>
<html>
<head>
@yield('head')
@yield('meta')
@yield('styles')
</head>
<body>
@include('themes::laravel-bootstrap.bootstrap._nav')
@yield('content')
<aside>
@yield('sidebar')
@yield('widgets')
</aside>
<footer>
    @yield('footer')
</footer>
@yield('scripts')
</body>
</html>